M48
; DRILL file {KiCad 7.0.2} date Wed May  8 22:38:05 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-08T22:38:05+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.710
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X158.625Y-90.185
X158.625Y-96.695
T2
X157.285Y-80.365
X157.285Y-106.515
T0
M30
